
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.4.5.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace crm_tgui.ViewModel {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class AddCustomerView : Terminal.Gui.Views.Window {
        
        private Terminal.Gui.Views.FrameView frameView;
        
        private Terminal.Gui.Views.Label lblfirstName;
        
        private Terminal.Gui.Views.TextField txtFirstName;
        
        private Terminal.Gui.Views.Label lblMiddleName;
        
        private Terminal.Gui.Views.TextField txtMiddleName;
        
        private Terminal.Gui.Views.Label lblLastName;
        
        private Terminal.Gui.Views.TextField txtLastName;
        
        private Terminal.Gui.Views.Label lblNationalId;
        
        private Terminal.Gui.Views.TextField txtLastName2;
        
        private Terminal.Gui.Views.Button btnSubmit;
        
        private void InitializeComponent() {
            this.btnSubmit = new Terminal.Gui.Views.Button();
            this.txtLastName2 = new Terminal.Gui.Views.TextField();
            this.lblNationalId = new Terminal.Gui.Views.Label();
            this.txtLastName = new Terminal.Gui.Views.TextField();
            this.lblLastName = new Terminal.Gui.Views.Label();
            this.txtMiddleName = new Terminal.Gui.Views.TextField();
            this.lblMiddleName = new Terminal.Gui.Views.Label();
            this.txtFirstName = new Terminal.Gui.Views.TextField();
            this.lblfirstName = new Terminal.Gui.Views.Label();
            this.frameView = new Terminal.Gui.Views.FrameView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Overlapped;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.None;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Title = "";
            this.frameView.Width = 71;
            this.frameView.Height = 20;
            this.frameView.X = 50;
            this.frameView.Y = 2;
            this.frameView.Visible = true;
            this.frameView.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.frameView.CanFocus = true;
            this.frameView.ShadowStyle = null;
            this.frameView.Data = "frameView";
            this.frameView.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.frameView.Title = "Add Customer";
            this.Add(this.frameView);
            this.lblfirstName.Width = Dim.Auto();
            this.lblfirstName.Height = Dim.Auto();
            this.lblfirstName.X = 5;
            this.lblfirstName.Y = 2;
            this.lblfirstName.Visible = true;
            this.lblfirstName.CanFocus = false;
            this.lblfirstName.ShadowStyle = null;
            this.lblfirstName.Data = "lblfirstName";
            this.lblfirstName.Text = "First Name:";
            this.lblfirstName.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.frameView.Add(this.lblfirstName);
            this.txtFirstName.Width = 49;
            this.txtFirstName.Height = 1;
            this.txtFirstName.X = 17;
            this.txtFirstName.Y = 2;
            this.txtFirstName.Visible = true;
            this.txtFirstName.CanFocus = true;
            this.txtFirstName.ShadowStyle = null;
            this.txtFirstName.Secret = false;
            this.txtFirstName.Data = "txtFirstName";
            this.txtFirstName.Text = "";
            this.txtFirstName.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.frameView.Add(this.txtFirstName);
            this.lblMiddleName.Width = Dim.Auto();
            this.lblMiddleName.Height = Dim.Auto();
            this.lblMiddleName.X = 5;
            this.lblMiddleName.Y = 5;
            this.lblMiddleName.Visible = true;
            this.lblMiddleName.CanFocus = false;
            this.lblMiddleName.ShadowStyle = null;
            this.lblMiddleName.Data = "lblMiddleName";
            this.lblMiddleName.Text = "Middle Name:t";
            this.lblMiddleName.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.frameView.Add(this.lblMiddleName);
            this.txtMiddleName.Width = 49;
            this.txtMiddleName.Height = 1;
            this.txtMiddleName.X = 17;
            this.txtMiddleName.Y = 5;
            this.txtMiddleName.Visible = true;
            this.txtMiddleName.CanFocus = true;
            this.txtMiddleName.ShadowStyle = null;
            this.txtMiddleName.Secret = false;
            this.txtMiddleName.Data = "txtMiddleName";
            this.txtMiddleName.Text = "";
            this.txtMiddleName.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.frameView.Add(this.txtMiddleName);
            this.lblLastName.Width = Dim.Auto();
            this.lblLastName.Height = Dim.Auto();
            this.lblLastName.X = 5;
            this.lblLastName.Y = 8;
            this.lblLastName.Visible = true;
            this.lblLastName.CanFocus = false;
            this.lblLastName.ShadowStyle = null;
            this.lblLastName.Data = "lblLastName";
            this.lblLastName.Text = "Last Name:";
            this.lblLastName.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.frameView.Add(this.lblLastName);
            this.txtLastName.Width = 49;
            this.txtLastName.Height = 1;
            this.txtLastName.X = 17;
            this.txtLastName.Y = 8;
            this.txtLastName.Visible = true;
            this.txtLastName.CanFocus = true;
            this.txtLastName.ShadowStyle = null;
            this.txtLastName.Secret = false;
            this.txtLastName.Data = "txtLastName";
            this.txtLastName.Text = "";
            this.txtLastName.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.frameView.Add(this.txtLastName);
            this.lblNationalId.Width = Dim.Auto();
            this.lblNationalId.Height = Dim.Auto();
            this.lblNationalId.X = 5;
            this.lblNationalId.Y = 11;
            this.lblNationalId.Visible = true;
            this.lblNationalId.CanFocus = false;
            this.lblNationalId.ShadowStyle = null;
            this.lblNationalId.Data = "lblNationalId";
            this.lblNationalId.Text = "National Id:";
            this.lblNationalId.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.frameView.Add(this.lblNationalId);
            this.txtLastName2.Width = 49;
            this.txtLastName2.Height = 1;
            this.txtLastName2.X = 17;
            this.txtLastName2.Y = 11;
            this.txtLastName2.Visible = true;
            this.txtLastName2.CanFocus = true;
            this.txtLastName2.ShadowStyle = null;
            this.txtLastName2.Secret = false;
            this.txtLastName2.Data = "txtLastName2";
            this.txtLastName2.Text = "";
            this.txtLastName2.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.frameView.Add(this.txtLastName2);
            this.btnSubmit.Width = Dim.Auto();
            this.btnSubmit.Height = Dim.Auto();
            this.btnSubmit.X = Pos.Center();
            this.btnSubmit.Y = 15;
            this.btnSubmit.Visible = true;
            this.btnSubmit.CanFocus = true;
            this.btnSubmit.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Opaque;
            this.btnSubmit.Data = "btnSubmit";
            this.btnSubmit.Text = "Submit";
            this.btnSubmit.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.btnSubmit.IsDefault = false;
            this.frameView.Add(this.btnSubmit);
        }
    }
}
